version: "3.7"

services:
  ################################
  # example: booking             #
  ################################
  trip-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: trip-api
    environment:
      TEMPORAL_HOST_PORT: "temporal:7233"
    ports:
      - 3000:3000
    depends_on:
      - temporal
    restart: always
  hotel-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: hotel-api
  car-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: car-api
  flight-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: flight-api
  ################################
  # example: worker(saga)        #
  ################################
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: worker
    environment:
      TEMPORAL_HOST_PORT: "temporal:7233"
      HOTEL_ENDPOINT: "http://hotel-api:3001"
      CAR_ENDPOINT: "http://car-api:3002"
      FLIGHT_ENDPOINT: "http://flight-api:3003"
    depends_on:
      - temporal
    restart: always
  ################################
  # temporal                     #
  ################################
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  temporal:
    image: temporalio/auto-setup:1.5.1
    environment:
      - DB=mysql
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - 7233:7233
    volumes:
      - ./config:/etc/temporal/config/dynamicconfig
    depends_on:
      - mysql
  temporal-admin-tools:
    image: temporalio/admin-tools:1.5.1
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    depends_on:
      - temporal
  temporal-web:
    image: temporalio/web:1.5.0
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - 8088:8088
    depends_on:
      - temporal
